# auto-generated by plugin sync
use ../lib/help.nu
const SKILL_DIR = (path self | path dirname)
# Plugin manager for zenix skills
export def main [] { help show plugin $SKILL_DIR }

export use install.nu
export use list.nu
export use remove.nu
export use sync.nu
export use update.nu
