# auto-generated by skill sync
use ../lib/help.nu
const SKILL_DIR = (path self | path dirname)
# Skill manager for zenix
export def main [] { help show skill $SKILL_DIR }

export use install.nu
export use list.nu
export use remove.nu
export use sync.nu
export use update.nu
export use verify.nu
